### ISSUE TITLE
Great cheat sheets, Would you consider contributing this to ros2_documentation?

### ISSUE THREAD

**Issue by kscottz** [artivis/ros2_cheats_sheet#3]
I think these would be great to have in the ROS 2 documentation. Perhaps we could cut a copy of the PDF as a release artifact. 

If you are interested let me know if I could help. This is a great resource.

**Comment by artivis** [comment]
@kscottz, 
thanks for reaching out.
The CLI cheat sheet has already landed on [ros2cli README](https://github.com/ros2/ros2cli#cheat-sheet). But i'd be happy if it serves in the ROS 2 documentation as well. How do you propose to proceed?

**Comment by kscottz** [comment]
Oh, it is already, in the CLI documentation? I didn't realize it was there, I just came across this while search for something else and I thought it was great. I think that should be sufficient. 

Anyway, thanks a ton for your great work.
